[package]
name = "bar_daemon_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"          # parse Rust code
quote = "1.0"        # generate Rust code
proc-macro2 = "1.0"  # needed by syn/quote